"""initial_schema

Revision ID: 09b8cd61ccec
Revises: 
Create Date: 2026-07-24 23:25:55.246261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09b8cd61ccec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fpl_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_teams_fpl_id'), 'teams', ['fpl_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fpl_entry_id', sa.Integer(), nullable=True),
    sa.Column('risk_profile', sa.String(length=50), nullable=False),
    sa.Column('encrypted_session_token', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_fpl_entry_id'), 'users', ['fpl_entry_id'], unique=True)
    op.create_table('fixtures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fpl_id', sa.Integer(), nullable=False),
    sa.Column('gameweek', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('difficulty_home', sa.Integer(), nullable=False),
    sa.Column('difficulty_away', sa.Integer(), nullable=False),
    sa.Column('kickoff_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fixtures_fpl_id'), 'fixtures', ['fpl_id'], unique=True)
    op.create_index(op.f('ix_fixtures_gameweek'), 'fixtures', ['gameweek'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fpl_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('second_name', sa.String(length=100), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('chance_of_playing_next_round', sa.Integer(), nullable=True),
    sa.Column('chance_of_playing_this_round', sa.Integer(), nullable=True),
    sa.Column('news', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_fpl_id'), 'players', ['fpl_id'], unique=True)
    op.create_table('user_transfer_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gameweek', sa.Integer(), nullable=False),
    sa.Column('free_transfers_banked', sa.Integer(), nullable=False),
    sa.Column('bank_balance', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'gameweek', name='uq_user_gameweek_transfer')
    )
    op.create_index(op.f('ix_user_transfer_state_gameweek'), 'user_transfer_state', ['gameweek'], unique=False)
    op.create_table('gameweek_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('gameweek', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('xg', sa.Float(), nullable=False),
    sa.Column('xa', sa.Float(), nullable=False),
    sa.Column('bonus', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'gameweek', name='uq_player_gameweek')
    )
    op.create_index(op.f('ix_gameweek_stats_gameweek'), 'gameweek_stats', ['gameweek'], unique=False)
    op.create_table('user_squads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gameweek', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('is_starting', sa.Boolean(), nullable=False),
    sa.Column('is_captain', sa.Boolean(), nullable=False),
    sa.Column('is_vice', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'gameweek', 'player_id', name='uq_user_gameweek_player')
    )
    op.create_index(op.f('ix_user_squads_gameweek'), 'user_squads', ['gameweek'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_squads_gameweek'), table_name='user_squads')
    op.drop_table('user_squads')
    op.drop_index(op.f('ix_gameweek_stats_gameweek'), table_name='gameweek_stats')
    op.drop_table('gameweek_stats')
    op.drop_index(op.f('ix_user_transfer_state_gameweek'), table_name='user_transfer_state')
    op.drop_table('user_transfer_state')
    op.drop_index(op.f('ix_players_fpl_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_fixtures_gameweek'), table_name='fixtures')
    op.drop_index(op.f('ix_fixtures_fpl_id'), table_name='fixtures')
    op.drop_table('fixtures')
    op.drop_index(op.f('ix_users_fpl_entry_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_teams_fpl_id'), table_name='teams')
    op.drop_table('teams')
    # ### end Alembic commands ###
